-- AlterTable
ALTER TABLE "Job" ADD COLUMN     "cvId" INTEGER DEFAULT 0;

-- AddForeignKey
ALTER TABLE "Job" ADD CONSTRAINT "Job_cvId_fkey" FOREIGN KEY ("cvId") REFERENCES "CvsFile"("id") ON DELETE SET NULL ON UPDATE CASCADE;
