// import { OfferData } from "../Types/Globals";


// export const jobDetails: OfferData[] = [
//     {
//     id: 1,
//     title: 'Responsable Audit h/f',
//     companyName : 'Sofitel',
//     contractType: 'CDI',
//     ville : 'Meknes',
//     domaine: 'imobilier',
//     studies : 'Niveau d’études: Bac +5 ',
//     experienceYears: '3 ans',
//     description: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s                         when an unof type and scrambled it to make a type                         specimen book. It has survived not only five centuries",
//     missions: [
//         'Lorem Ipsum is simply dummy text',
//         'Lorem Ipsum is simply dummy text',
//         'Lorem Ipsum is simply dummy text', 
//     ],
//     profil: [
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//     ],
//     avantages: [
//         'Salaire 9000DH',
//         'Cnss',
//         'Intern Gym',
//     ],
// },
//     {
//     id: 2,
//     jobTitle: 'DevOps',
//     companyName : 'maltem',
//     contract: 'stage',
//     ville : 'rabat',
//     domaine: 'tourisme',
//     studies : 'Niveau d’études: Bac +5 en tourisme',
//     experienceYears: '5 ans',
//     description: " Ipsum is simply dummy text of the printing and typesetting industry.Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s                         when an unknown printer took a galley of type and scrambled it to make a type                         specimen book. It has survived not only five centuries",
//     missions: [
//         'Lorem Ipsum is simply dummy text',
//         'Lorem Ipsum is simply dummy text',
//         'Lorem Ipsum is simply dummy text', 
//     ],
//     profil: [
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//     ],
//     avantages: [
//         'Salaire 9000DH',
//         'Cnss',
//         'Intern Gym',
//     ],
    
// },
//     {
//     id: 3,
//     jobTitle: 'Agriculture ',
//     companyName : 'OCP',
//     contract: 'CDD',
//     ville : 'Tanger',
//     domaine: 'Agriculture',
//     studies : 'Niveau d’études: Bac +5 en Agriculture',
//     experienceYears: '5 ans',
//     description: "Lorem Ipsum is simply duing and typesetting industry.Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s                         when an unknown printer took a galley of type and scrambled it to make a type                         specimen book. It has survived not only five centuries",
//     missions: [
//         'Lorem Ipsum is simply dummy text',
//         'Lorem Ipsum is simply dummy text',
//         'Lorem Ipsum is simply dummy text', 
//     ],
//     profil: [
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//     ],
//     avantages: [
//         'Salaire 9000DH',
//         'Cnss',
//         'Intern Gym',
//     ],
// },
//     {
//     id: 4,
//     jobTitle: 'caissier',
//     companyName : 'alten',
//     contract: 'Anapec',
//     ville : 'oujda',
//     domaine: 'finance',
//     studies : 'Niveau d’études: Bac +2 en Gestion ',
//     experienceYears: '5 ans',
//     description: "Lorem Ipsum is simply dummy text of the printing a industry.Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s                         when an unknown printer took a galley of type and scrambled it to make a type                         specimen book. It has survived not only five centuries",
//     missions: [
//         'caissier caissier caissier caissier',
//         ' caissiercaissiercaissiercaissier',
//         'Lorem Ipsum is simply dummy text', 
//     ],
//     profil: [
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//     ],
//     avantages: [
//         'Salaire 4000DH',
//         'Cnss',
        
//     ],
// }, 
//     {
//     id: 5,
//     jobTitle: 'Infermiere',
//     companyName : 'Ibn Sina',
//     contract: 'Freelance',
//     ville : 'Casablanca',
//     domaine: 'Santé',
//     studies : 'Niveau d’études: Bac +3',
//     experienceYears: '3 ans',
//     description: "Lorem Ipsum is  the printing and typesetting industry.Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s                         when an unknown printer took a galley of type and scrambled it to make a type                         specimen book. It has survived not only five centuries",
//     missions: [
//         'Lorem Ipsum is simply dummy text',
//         'Lorem Ipsum is simply dummy text',
//         'Lorem Ipsum is simply dummy text', 
//     ],
//     profil: [
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//         'Lorem Ipsum has been the industry\'s',
//     ],
//     avantages: [
//         'Salaire 7000DH',
//         'Cnss',
        
//     ],
// },
// ]
